name: Fetch and Save Apartment Data

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pandas

      - name: Run Python script to generate SQL
        env:
          API_KEY: ${{ secrets.SERVICE_KEY }}
        run: python fetch_data.py
        
      - name: Commit and push SQL file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: Update apartment trade data SQL file"
          file_pattern: 'apt_trade.sql'
